### ISSUE TITLE
Installing kardinal gives 'project is no longer active' error 

### ISSUE THREAD

**Issue by markdane22** [kurtosis-tech/kardinal#287]
Hi team, when I am trying to install the kardinal using the command(`curl get.kardinal.dev -sL | sh`) given in the docs, it is giving error : 
`The Kardinal project is no longer active`

**Comment by laurentluce** [comment]
This project is no longer maintained and we do not have time anymore to support the existing binaries.  Our recommendation is to fork the repo, build it and install it on your own.
